# -*- coding: utf-8 -*-
"""Copy of Play-store-project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZYso-bjLhT4kp7S0PuXLiULcs59FpG_a

##Importing Packages
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
# import

"""#Loading the Dataset"""

df = pd.read_csv('/content/playstore-analysis.csv')
df

sns.heatmap(df.isnull())

"""#Exploring the dataset"""

type(df['Current Ver'][0])

df.columns

# df = df.set_index('App') #if neccessary

df.info()

df.describe()

df.isna().sum()

df.shape

df.size

df['Rating'].replace(np.NaN,0,inplace=True)

df['Rating']

df['Rating'].isna().sum()

# df.dropna(inplace=True,axis=0) drops all null values of the dataset

# df.drop('Rating',inplace = True,axis=1) deleting the column rating **no need

# df['Rating'] = df['Rating'].dropna() #removes the null values

# df.dropna(inplace=True)
df['Rating'].isna().sum()
df['Rating'].shape

df.isna().sum()

df.count()

"""#Visuaizing the rating plot"""

plt.plot(df['Rating'])

"""#Check the null values for the Android Ver column."""

df.columns

df['Android Ver']

"""i. Are all 3 records having the same problem?

Yes all  three values are null
"""

k = df['Android Ver'].isna().sum()
k# 3 null values present

"""ii. Drop the 3rd record i.e. record for “Life Made WIFI …”

"""

df['App']

# Life= df['App'].sort_values()

for i in df['App']:
  if (i=='Life Made WI-Fi Touchscreen Photo Frame'):
    Life= df['App'].sort_values()
    print(Life)
    del df['App'][3]

# plt.plot(df['App'])
# plt.show()

"""iii. Replace remaining missing values with the mode"""

df['Android Ver'] = df['Android Ver'].fillna(df['Android Ver'].mode()[0])

df['Android Ver'].isna().sum()

df['Android Ver']

"""c. Current ver – replace with most common value"""

df['Current Ver']

# df['Current Ver'].dtype
type(df['Current Ver'])

df.Size.nunique()#Make a column with a single unit of size in column size

# df['Current Ver'] = df['Current Ver'].replace({"Varies with device":''}, regex=True)
# df['Current Ver'].nunique()

for i in df['Current Ver']:
  print(i)

# for i in df['Current Ver']:
#   # print(i)
#   # al =
#   df['Current Ver'] = drop(df['Current Ver'][i].isalpha(),axis=0,inplace=True,errors=ignore)

df=df[ df['Current Ver'].str.contains('Varies with device')==False ]

df['Current Ver']

df['Current Ver'].unique()

from string import ascii_letters

for i in ascii_letters:
  print(i)

for i in ascii_letters:
  # print(i)
  for j in df['Current Ver']:
    if str(df['Current Ver'][j]) in i:
        print(df['Current Ver'][j])
  else:
        print(df['Current Ver'][j])

print(df['Current Ver'][i])

ascii_letters

for i in range(len(df['Current Ver'])):
  if df['Current Ver'][i].isapha() and df['Current Ver'][i].isspace():
    df['Current Ver'][i]=0
      print(i)

a[0:3].isalpha()

for i in range(len(df['Current Ver'])):
  if df['Current Ver'][i].isapha():
    df['Current Ver'][i]=0
      print(i)

a = ['1.4', '1.01.1','22.3','4.4.4.6',0,0,0,0,0,0,0]
a = [i for i in a if (i!=0)]
for i in range(len(a)):
  a[i]=float(a[i][0:3])
print(a)

# a = ['1.4', '1.01.1','22.3','4.4.4.6',0,0,0,0,0,0,0]
a = ['1.4', '1.0.1','2.3','4.4.4.6','series of values','alphabets']
def rep():
    if a[i][0:3].isalpha():
       a[i]=''
for i in range(len(a)):
    rep()

print(a)

# a = ['1.4', '1.01.1','22.3','4.4.4.6',0,0,0,0,0,0,0]
[float('.'.join((i.split('.')[:2]))) for i in a if (i!='')]

a = ['1.4', 'a1.0.1','2.3a','4.4.4.6','series of values','alphabets']
def rep():
    if a[i][0:4].isalpha():
       print(a[i])
       a[i]=''
    elif
for i in range(len(a)):
    rep()

print(a)

import re
for i in a:
  x = re.findall("[a-zA-Z]", i)
  print(x)

# a = ['1.4', '1.01.1','22.3','4.4.4.6',0,0,0,0,0,0,0]
[float('.'.join((i.split('.')[:2]))) for i in a if (i!='')]

import re

a = ['1.4', 'a1.0.1','2.3a','4.4.4.6','series of values','alphabets']

for i in a:
  x = re.findall("[^[a-zA-Z]]?", str(i))
  y = [float(','.join((i.split('.')[:2]))) for i in x if (i!='')]
  # print(type(i))
  print(y)

[float('.'.join((i.split('.')[:2]))) for i in x if (i!='')]

[float('.'.join((i.split('.')[:2]))) for i in a if (i!='')]

df

a = ['1.4', '1.0.1','2.3','4a.4.4.6','series of values','alphabets']
def rep():
    if a[i][0:3].isalpha():
       a[i]=0


for i in range(len(a)):
    rep()



print(a)

a = ['1.4', '1.01.1','22.3','4.4.4.6',0,0,0,0,0,0,0]
a = [i for i in a if (i!=0)]
for i in range(len(a)):
  a[i]=float(a[i][0:3])
print(a)

a = ['1.4', '1.01.1','22.3','4.4.4.6',0,0,0,0,0,0,0]
aa = [i for i in a if (i!=0)]

for i in aa:
 print('.'.join((i.split('.')[:2])))

aa = [i for i in df['Current Ver'] if (i!=0)]

for i in aa:
 print('.'.join((i.split('.')[:2])))

for i in df['Current Ver']:
  print(i.split('.'))

[float('.'.join((i.split('.')[:2]))) for i in df['Current Ver'] if (i!='')]

for i in df['Current Ver']:
  def rep():
    if df['Current Ver'][i][0:3].isalpha():
       df['Current Ver'][i]=''
for i in range(len(df['Current Ver'])):
    rep()

print(df['Current Ver'])

for i in df['Current Ver']:
  def rep():
    if df['Current Ver'][i][0:].isalpha():
       df['Current Ver'][i]=''
for i in range(len(df['Current Ver'])):
    rep()

print(df['Current Ver'])

df['Current Ver']=df['Current Ver'].astype('float')

df['Current Ver'].mean()

# df['Current Ver']=df['Current Ver'].apply(lambda x: str(x).replace('Varies with device', '0'))
# df['Current Ver']=df['Current Ver'].apply(lambda x: str(x).fillna(df['Current Ver'].mean()))

# df['Current Ver'] = df['Current Ver'].replace({"Varies with device":''}, regex=True)
# df['Current Ver'].nunique()

df['Current Ver'].replace(to_replace="Varies with device", mean(), inplace = True)

df['Current Ver']=df['Current Ver'].apply(lambda x: str(x).replace('Varies with device', '0'))
df['Current Ver']=df['Current Ver'].apply(lambda x: str(x).fillna(df['Current Ver'].mean()))

df['Current Ver']= pd.to_numeric(df['Current Ver'])

def mean_val(a):
  for j in df['Current Ver']:
    if (j=='Varies with device'):
      df['Current Ver'] = df['Current Ver'].replace('Varies with device',np.nan)
      df['Current Ver'] = df['Current Ver']= pd.to_numeric(df['Current Ver'])
      df['Current Ver'] = df['Current Ver'].fillna(df['Current Ver'].mean())


      # print(df['Current Ver'])

for j in df['Current Ver']:
  if (j=='Varies with device'):
    df['Current Ver'] = df['Current Ver'].replace('Varies with device',np.nan).fillna(df['Current Ver'].mean())
    # df['Current Ver'] = df['Current Ver']

df['Current Ver'] = df['Current Ver'].replace({"Varies with device":np.nan}, regex=True)
df['Current Ver'].nunique()

df['Current Ver']

df['Current Ver'].replace(to_replace="Varies with device", value= '1M', inplace = True)

# data['S'] = data['Size'].str[-1:]
# data.S.unique()

df['Current Ver'] = df['Current Ver']= pd.to_numeric(df['Current Ver'])

df['Current Ver'] = df['Current Ver'].fillna(df['Current Ver'].mean())

df.Size.nunique()#Make a column with a single unit of size in column size

import re

for i in df['Current Ver']:
  x = re.findall("[^[a-zA-Z]]?", str(i))
  # print(type(i))
  print(x)

for i in df['Current Ver']:
  print(i)

"""##2. Data clean up – correcting the data types

a. Which all variables need to be brought to numeric types?

Here Object needs to be converted into numeric()
"""

df.Size=df.Size.apply(lambda x: str(x).replace('Varies with device', '0'))
df.Size=df.Size.apply(lambda x: str(x).replace('M', '') if 'M' in str(x) else x)
df.Size=df.Size.apply(lambda x: str(x).replace(',', '') if 'M' in str(x) else x)
df.Size=df.Size.apply(lambda x: float(str(x).replace('k', '')) / 1000 if 'k' in str(x) else x)
df.Size=pd.to_numeric(df.Size)

sns.boxplot(df['Size'])

df.info()

# df['Discount'] = pd. to_numeric(df['Discount'])

"""b. Price variable – remove $ sign and convert to float"""

df['Price']

df.Price.value_counts()

df['Price']=df['Price'].str.strip()

df['Price'] = df['Price'].str.replace('$', '')
df.Price.value_counts()

df['Price']=pd.to_numeric(df['Price'])

plt.plot(df['Price'])

"""c. Installs – remove ‘,’ and ‘+’ sign, convert to integer

"""

df['Installs']

df['Installs'].count()

df.Installs=df.Installs.map(lambda x:x.replace(',','').replace('+',''))

df['Installs']

# df['Installs'].astype(int(df['Installs']))

"""d. Convert all other identified columns to numeric"""

df.columns

df['Category'].astype(int)

# df.dropna(inplace=True)
# print(df.shape)

df['Size']

"""#3. Sanity checks – check for the following and handle accordingly

a. Avg. rating should be between 1 and 5, as only these values are allowed on the play
store.

i. Are there any such records? Drop if so.
"""

df.columns

df['Rating']

df['Rating'].isna().sum()

# for i in df['Rating']:
#   # print(i)
#   if i > 1 and i<5:
#     print(i)

print(len(df[df.Rating>5]))
print(len(df[df.Reviews>df.Installs]))

df=df[df.Reviews<df.Installs]
print(df.shape)

"""b. Reviews should not be more than installs as only those who installed can review the
app.



i. Are there any such records? Drop if so.
"""

df['Reviews']

df.Reviews=df.Reviews.astype('float')

df.Installs=df.Installs.astype('float')

c=df.Reviews>df.Installs

c.value_counts()

df[df['Installs'] - df['Reviews'] < 0]

# (df.Reviews<df.Installs).value_counts()

indexNames = df[ df['Installs'] - df['Reviews'] < 0 ].index
df.drop(indexNames , inplace=True)

# df['Reviews'] = df['Installs']<=df['Reviews']
# df['Reviews']

df['Reviews'].isna().sum()

df['Reviews']= pd.to_numeric(df['Reviews'])

plt.plot(df['Reviews'])

sns.distplot(a=df['Rating'], kde=False)

"""#4. Identify and handle outliers –

a. Price column

i. Make suitable plot to identify outliers in price
"""

df['Price']

sns.boxplot(df['Price'])

"""ii. Do you expect apps on the play store to cost $200? Check out these cases"""

df=df[df.Price<200]
print(df.shape)

df['Price']

df.Price.value_counts()

indexNames = df[df['Price'] >= 200].index
df.drop(indexNames , inplace=True)

"""iii. After dropping the useless records, make the suitable plot again to identify outliers"""

sns.boxplot(df['Price'])

"""iv. Limit data to records with price < $30"""

df['Price'] = df.Price<=30
df['Price'].value_counts()

"""#b. Reviews column

i. Make suitable plot
"""

plt.plot(df['Reviews'])

sns.boxplot(df['Reviews'])

"""ii. Limit data to apps with < 1 Million reviews"""

d = df.Reviews<1000000
d.value_counts()

sns.boxplot(df['Reviews'])

"""#c. Installs

i. What is the 95th percentile of the installs?
"""

percentiles=df['Installs']

print("95th percentile : ",
       np.percentile(percentiles, 95))

"""ii. Drop records having a value more than the 95th percentile"""

#remove outliers
indexOut = df[df['Installs'] >= np.percentile(percentiles, 95)].index
df.drop(indexOut , inplace=True)
#verify
df.shape

percentiles

sns.boxplot(percentiles)

"""Visualisation - Data Analysis"""

corr1=df.corr()r
sns.heatmap(corr1, cmap="YlOrBr")

df.boxplot()

plt.figure(figsize=(25,8))
sns.boxplot(df["Content Rating"],df["Rating"])
plt.show()

col = ['Rating','Size','Price']
plt.figure(figsize=(18,12))
for i,v in enumerate(col):
    print(i,v)
    plt.subplot(3,2,i+1)
    sns.boxplot(x=v, data=df)
plt.show()

print(df.hist(['Rating','Reviews','Size','Installs','Price'],figsize=(12,8),xlabelsize=12,ylabelsize=12))
plt.plot()

df.shape

(600/10841 )*100

"""Gradient desent"""

import matplotlib.pyplot as plt
import numpy as np

import scipy
from scipy.misc import derivative

def f_prime(x):
  f_derivative = derivative(func, x)
  return f_derivative

# Below is the function to converge the gradient
def gradient_converge(eta , gradient_x, iterations):
  for i in range(0,iterations):

      # The derivative is the rate of change or the slope of a function at a given point
      deriv_x = f_prime(gradient_x)
      # Calculating the gradient_x = x - eta * f'(x)
      gradient_x = gradient_x - eta * deriv_x

  return gradient_x

iterations = 600

# Set an initial value, to start with
Initial_point = 6

# Learning rate
eta = 0.001

# Calling the gradient_converge() function
gradient_x = gradient_converge(eta, Initial_point, iterations)
print("iterations = ",iterations,"\ngradient_x = ",gradient_x)

plt.plot(X, Y, marker='o',color='b',linestyle='-');
plt.plot(X, Y, 'o', color='r');
y_gradient = func(gradient_x)
plt.plot(gradient_x, y_gradient,'ko',  markersize = 10)
plt.show()

